WIP: Add JS(X)/TS(X) linting
hello-robot/stretch_web_teleop pull request #45
Opened 2024-05-21 22:07 UTC by hello-amal

# Description

This PR, in partial service of #43 , builds off of #44 to add JS(X)/TS(X) linting.

This PR is a work-in-progress; although the pre-commit hooks are properly configured to lint the repository (and that has been tested), they generate hundreds of warnings/errors. Most are straightforward to fix, but some fixes require legacy knowledge of the codebase (e.g., [the fact that `relativePose` no longer exists as a type](https://github.com/hello-robot/stretch_web_teleop/blob/34ff6810f768c120f7b0b17105df699f07ab15af/src/pages/operator/tsx/index.tsx#L157)). Those lint errors are better suited for @hello-vinitha to address.

# Testing procedure

TODO

# Before opening a pull request

From the top-level of this repository, run:

- \[ \] `pre-commit run --all-files`

# To merge

- \[ \] `Squash & Merge`

2024-05-22 00:06 UTC, hello-amal commented
At this point, CI is (rightly) failing due to the linting errors. But CI configuration is correct.

2025-05-06 20:30 UTC, hello-binit commented on .github/workflows/pre-commit.yaml
> +      - name: Commit auto-fixes
Yes, I strongly feel the action should not commit and push fixes on its own. Failing out is sufficient. I recommend we don't merge this PR until this is changed.

2025-05-06 20:30 UTC, hello-binit requested changes
I strongly feel the action should not commit and push fixes on its own. Failing out is sufficient. I recommend we don't merge this PR until this is changed.

2025-05-08 22:55 UTC, hello-william commented
crud...  sorry guys... i'll get to this first thing tmrw!

2025-05-08 23:11 UTC, hello-vinitha commented on .github/workflows/pre-commit.yaml
> +      - name: Commit auto-fixes
I agree with @hello-binit

2025-05-09 19:09 UTC, hello-william commented
@hello-binit @hello-robot-shehab

i removed auto-fixing/auto-committing

it will exit 0, and provide a diff

2025-05-09 21:32 UTC, hello-binit approved these changes
Thanks for getting this going @hello-william!!

2025-05-09 21:38 UTC, merged

2025-05-15 17:53 UTC, hello-william commented
@hello-robot-shehab did you check the github action output?

there could be errors that need to be addressed before it will allow you to merge 

https://github.com/user-attachments/assets/b6caeaa1-4f02-4e76-811e-e471af5f2f6c

2025-05-15 18:00 UTC, hello-william commented
@hello-robot-shehab np! :]

most of the linting rules are OOTB but i'm pretty sure vinitha/binit are cool with changing those lint rules if they're too burdensome... just lemme know and i can change those rules